### ISSUE TITLE
How to solve this error?

### ISSUE THREAD

**Issue by CRC32EX** [getkey/rollup-plugin-obfuscator#7]
# Steps to reproduce this issue

1. Init Vue3 project
```
npm init vue@latest
```
![image](https://user-images.githubusercontent.com/25629617/160607472-94954216-5b1b-4c96-93a4-7dee9f195140.png)

2. Install modules
```
cd vue-project
npm install
npm install --save-dev rollup-plugin-obfuscator javascript-obfuscator
```

3. Edit vite.config.ts
```
vim vite.config.ts
```
![image](https://user-images.githubusercontent.com/25629617/160617561-98347257-d005-45c8-9dc9-65b249760ea2.png)

4. Build
```
npm run build
```

5. Error
```
vite v2.8.6 building for production...
✓ 6 modules transformed.
[rollup-plugin-obfuscator] Line 4: Unexpected token import
> ...ateWebHistory(import.meta.env....
file: C:/Users/user01/Desktop/vue-project/src/router/index.ts
error during build:
Error: Line 4: Unexpected token import
> ...ateWebHistory(import.meta.env....
    at Function.processParsingError (C:\Users\user01\Desktop\vue-project\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\EspreeFacade.ts:100:15)
    at Function.parse (C:\Users\user01\Desktop\vue-project\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\EspreeFacade.ts:44:46)
    at e.parseCode (C:\Users\user01\Desktop\vue-project\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:151:29)
    at e.obfuscate (C:\Users\user01\Desktop\vue-project\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:132:46)
    at Object.value [as obfuscate] (C:\Users\user01\Desktop\vue-project\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscatorFacade.ts:31:70)
    at Object.exports.default.transform (C:\Users\user01\Desktop\vue-project\node_modules\rollup-plugin-obfuscator\src\rollup-plugin-obfuscator.ts:52:38)
    at C:\Users\user01\Desktop\vue-project\node_modules\rollup\dist\shared\rollup.js:22779:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by vuolter** [comment]
In my use-case setting `global: true` fixed it.
